### ISSUE TITLE
How to keep the loader in this repo in sync with the main repo

### ISSUE THREAD

**Issue by looeee** [threejs/lwoloader-test-models#2]
While this repo is going to be very useful for developing the loader, it does introduce two copies of the loader. The one on the main three.js repo should be considered the canonical repo. To keep them in sync, we have a couple of options:

1. Somehow link the main  file from the repo, and make all changes as incremental PRs to the main three.js repo. [Git submodules](https://github.blog/2016-02-01-working-with-submodules/) might work for this, I'm not sure about that though. 

2. Version the loader using semver. Current version = 1.0.0 (major.minor.patch). Changes on this repo will be patches - so if we fix a bug we'll bump it to 1.0.1. Then, once a month or so we'll do a minor update (1.1.0) and also update the main loader on the repo. This is the simper option, and means that we can always ensure that the main loader is working correctly, while if we break something with a patch update it's not a big deal.

**Comment by sciecode** [comment]
Given the current ongoing development and re-structure of the loader, I believe semver offers us more flexibility and security. 

Semver would also be preferable if we decide to go for a modular approach. Keeping things linked properly whilst modular may be a bit of a challenge. Especially considering single-file constraint over main repo. 

With version management we can just build a bundled single file every time we release a minor update.

**Comment by looeee** [comment]
Yeah, that makes sense. OK, let's do that.
