### ISSUE TITLE
Split the loader up into modules and add a build process

### ISSUE THREAD

**Issue by looeee** [threejs/lwoloader-test-models#3]
It would make sense to split the loader into (at least) two pieces - the IFF parser and the rest. 
Once we do that we'll have to add a build process. To keep things simple and in sync, we can copy the build process from the main repo - that it, use the same rollup config. 

I'm open to other suggestions of how to modularise it too, and also how best to create the LWO2 and LWO3 loaders while minimising code duplication.

**Comment by sciecode** [comment]
>I'm open to other suggestions of how to modularise it too, and also how best to create the LWO2 and LWO3 loaders while minimising code duplication.

I'm in favor of just creating two different IFFparsers, one for each version. The rest of the code isn't version specific. With that being said, some `CHUNK` cases are expected to be duplicated.

I believe the pros of working on a modular file (not risking breaking the other versions) outweigh the cons (changes on duplicated cases, around 10-15, require changes on both modules).

>To keep things simple and in sync, we can copy the build process from the main repo - that it, use the same rollup config.

I do agree with the use of rollup as our build-bundler. Although, while testing it, I noticed that imported modules are always bundled to the top of the file. Pushing `THREE.LWOLoader` declaration to the bottom of the file. I couldn't find a way to reverse this. Not sure what to make of this.

**Comment by looeee** [comment]
>  Although, while testing it, I noticed that imported modules are always bundled to the top of the file

That's correct, I believe. Functions and classes in JS always need to be declared before they are used. Unfortunately to us humans that makes it look like it's backwards. 

```js
function IFFParser(){
}

function GeometryBuilder() {
}

function LWOLoader(){
  IFFParser();
  GeometryBuilder();
}

```

We'd rather read this the other way around with `LWOLoader` at the top, and often structure files in the "wrong" order for ease of readability. Generally it's fine to do that, but it may cause problems in scope hoisting, so the bundler does it in the technically correct order.

**Comment by sciecode** [comment]
Yes, this is the ES6 module import/export recommended behavior. But it does indeed make it harder for other people to follow along. Do you foresee this as being problem in the future? or is it a minor concern?

**Comment by sciecode** [comment]
Small correction. `MaterialParser` is also "sort of" version specific. 
The LWO2 material parsing version is an incomplete version of the LWO3 material parsing. 
It looks like we could, after expanding LWO2 support, use the same `parseMaterial` function for both versions. The current amount of version specific code does not issue a modular separation at the moment.

**Comment by looeee** [comment]
> Yes, this is the ES6 module import/export recommended behavior. But it does indeed make it harder for other people to follow along. Do you foresee this as being problem in the future? or is it a minor concern?

It's the behaviour of all bundled JS code. We don't need to worry about the compiled code being readable (too much) - people should be reading the source, not compiled code. So I'd mark this as "not a concern".
