### ISSUE TITLE
Location of images to be loaded

### ISSUE THREAD

**Issue by jds580s** [threejs/lwoloader-test-models#4]
Could we explore the best way to locate images.

Some quick background:
Currently when working in Lightwave the file structure looks like this:
[Project Folder aka Content Directory]
>[Images directory - can be set to any name but default is "Images"]
>[Objects directory - can be set to any name but default is "Objects"]
>[+ other asset directories that are less relevant in terms of this loader]

Objects do not store the location of the content directory in order to keep them portable. They also don't store their own location (object directory), if I am not mistaken so they can be freely copied and moved into sub directories without any missing file consequences due to relative paths that are no longer valid.  But, they do contain the path to each image relative to the content directory.  (One minor exception being if an image is used that lives outside of the content directory it's full local path is stored instead, which would obviously fail when loading remotely, but that is to be expected).

My hope in commissioning this loader was to have it serve as a bridge between Lightwave and three.js.  Where a user could hit save in Lightwave, refresh in the browser and see the changes immediately in browser without having to reorganize files before deploying.  That speeds up my development and iterating so much.

Can you help me understand the thought process of having the images directory stored as a sub directory of the model location?  That seems atypical compared to most of the three.js work I've done, though it does line up with some of the loader example files in the main repo (3ds, awd, md2, and xfile), the rest seem store textures alongside the objects for instance.

What would you think about adding an optional flag when loading a .lwo to indicate one or more of the following:
1. Ignore all texture paths and assume them to be in the same directory as the model (could be useful for the LWOLoader demo page on the main repo)
2. Use path relative to the model's location (what it's doing currently)
3. Use path relative to the displayed page (what I would like to see and mimics how Lightwave works)

**Comment by sciecode** [comment]
You are indeed correct, even the default structure is not currently being handled correctly. 

Right now we are assuming the `/images` folder is in the same directory as the model file.
The loader, currently, performs a check to determine if the relative texture path starts with "images". 
If so, it keeps current relative path (from the model folder, not the parent). If not, it assumes the texture to be in the same folder as the model.

I believe the default Lightwave structure should indeed be the standard for the loader. But allow me to propose an ordered list of how the loader behave:

1. Content path specified on creation `THREE.LWOLoader( manager, { imagesPath: 'any/folder/' } );`
2. Else, use default Lightwave structure. Can be detected by the model's parent directory (Objects).
3. Else, ignore texture paths and use same directory as the model.

When all of these fail, we provide an error suggesting the use of `imagesPath` to determine textures content directory.

**Comment by jds580s** [comment]
I like that proposed order.  The only adjustment that might need consideration for point 2:
If a model is in a sub directory within Objects, it's parent directory wouldn't correspond with the actual root content directory.
Perhaps it's still a good enough approach, and cases like that can be addressed using imagesPath.

Either way, I like it.

**Comment by sciecode** [comment]
Exactly. Models would need to be tied to `\Objects` directory or sub-directories, if we rely on parsing the model url (default behaviour). 

Maybe `imagesPath` can be non-intuitive when re-naming folders, I believe adding `rootPath` is easier to understand and we can simply use the texture path stored on the model.

A little warning though, if we change current default structure it will invalidate every single legacy project that updates current loader on main repo. Given that it is for the best and we provide a informing error message and comments. I don't see as that being a problem. Thoughts @looeee ?

**Comment by jds580s** [comment]
I suspect the impact of a change at this stage will be somewhere between minimal and none.  The loader only went public 15 days ago.  I've used it on 1 live project and two in-production projects, but would be glad to update with any new syntax necessary.
We'll just need to be sure to update the LWO demo file as well.

One note, I didn't use the default LW  Images directory for all the models I provided.  Instead I modified it to lowercase "images" since that would match up with most web projects standard images folder and won't cause a conflict on Windows systems where Images and images can't reside next to one another.

**Comment by sciecode** [comment]
> The loader only went public 15 days ago.

I didn't know that. In that case, I'll merge pull request. 

> I didn't use the default LW Images directory for all the models I provided

I took the liberty of changing the LW Images to uppercase.  Hope it's alright with you.

>... won't cause a conflict on Windows systems

Good catch, I've been developing under windows the past few days and I indeed missed that. 
Already fixed this issue.
